-- Kích hoạt extension để sinh UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. BẢNG NGƯỜI DÙNG
CREATE TABLE NGUOIDUNG (
    MaND SERIAL PRIMARY KEY,
    TenDangNhap VARCHAR(100) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE,
    MatKhau VARCHAR(255), -- cho phép NULL nếu user đăng nhập bằng Google
    GoogleSub VARCHAR(100) UNIQUE, -- ID duy nhất từ Google
    AnhDaiDien TEXT,
    LoaiDangNhap VARCHAR(20) DEFAULT 'local', -- local hoặc google
    VaiTro VARCHAR(50) DEFAULT 'user',
    TrangThai VARCHAR(20) DEFAULT 'active',
    ThoiGianTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. BẢNG VIDEO YOUTUBE
CREATE TABLE VIDEO (
    MaVideo SERIAL PRIMARY KEY,
    YouTubeID VARCHAR(50) UNIQUE NOT NULL,
    LinkVideo VARCHAR(500) NOT NULL,
    TieuDe TEXT,
    Kenh VARCHAR(255),
    ThoiLuong INTEGER,
    NgayDang TIMESTAMP,
    NoiDungGoc TEXT,
    NoiDungTomTat JSONB,
    ThoiGianThem TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. BẢNG CÔNG VIỆC XỬ LÝ (TASK HISTORY)
CREATE TABLE CONGVIEC_XULY (
    MaCongViec SERIAL PRIMARY KEY,
    TaskID UUID UNIQUE NOT NULL,
    MaVideo INTEGER REFERENCES VIDEO(MaVideo) ON DELETE CASCADE,
    MaND INTEGER REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    SoLuongBLYeuCau INTEGER,
    TrangThai VARCHAR(50), -- PENDING, PROCESSING, SUCCESS, FAILED
    KetQuaDashboard JSONB,
    ThoiGianBatDau TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianKetThuc TIMESTAMP
);

-- 4. BẢNG BÌNH LUẬN THÔ
CREATE TABLE BINHLUAN (
    MaBinhLuan SERIAL PRIMARY KEY,
    MaVideo INTEGER REFERENCES VIDEO(MaVideo) ON DELETE CASCADE,
    BinhLuanID VARCHAR(100),
    NoiDung TEXT NOT NULL,
    TacGia VARCHAR(255),
    ThoiGianDang TIMESTAMP NOT NULL,
    SoLike INTEGER DEFAULT 0,
    ThoiGianThuThap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_Video_BinhLuan UNIQUE (MaVideo, BinhLuanID)
);

-- 5. BẢNG PHÂN TÍCH CẢM XÚC
CREATE TABLE PHANTICH_CAMXUC (
    MaPhanTich SERIAL PRIMARY KEY,
    MaBinhLuan INTEGER REFERENCES BINHLUAN(MaBinhLuan) ON DELETE CASCADE,
    MaCongViec INTEGER REFERENCES CONGVIEC_XULY(MaCongViec) ON DELETE CASCADE,
    NhanCamXuc VARCHAR(20),
    DiemCamXuc FLOAT,
    CumChuDe VARCHAR(50),
    ThoiGianPhanTich TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_BinhLuan_CongViec UNIQUE (MaBinhLuan, MaCongViec)
);

-- 6. BẢNG LỊCH SỬ HỎI ĐÁP (CHATBOT)
CREATE TABLE HOIDAP (
    MaHoiDap SERIAL PRIMARY KEY,
    MaVideo INTEGER REFERENCES VIDEO(MaVideo) ON DELETE CASCADE,
    MaND INTEGER REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    MaCongViec INTEGER REFERENCES CONGVIEC_XULY(MaCongViec) ON DELETE CASCADE,
    CauHoi TEXT NOT NULL,
    CauTraLoi TEXT NOT NULL,
    NguonDuLieu JSONB,
    ThoiGianHoi TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. BẢNG QUÊN MẬT KHẨU
CREATE TABLE QUENMATKHAU (
    MaReset SERIAL PRIMARY KEY,
    MaND INTEGER NOT NULL REFERENCES NGUOIDUNG(MaND) ON DELETE CASCADE,
    Token VARCHAR(255) UNIQUE NOT NULL,
    ThoiGianTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ThoiGianHetHan TIMESTAMP NOT NULL,
    DaSuDung BOOLEAN DEFAULT FALSE
);

-- Đánh Index để tối ưu truy vấn
CREATE INDEX idx_binhluan_video ON BINHLUAN(MaVideo);
CREATE INDEX idx_congviec_nd ON CONGVIEC_XULY(MaND);
CREATE INDEX idx_phantich_nhan ON PHANTICH_CAMXUC(NhanCamXuc);
CREATE INDEX idx_quenmatkhau_mand ON QUENMATKHAU(MaND);
CREATE INDEX idx_quenmatkhau_token ON QUENMATKHAU(Token);
CREATE INDEX idx_nguoidung_google_sub ON NGUOIDUNG(GoogleSub);
CREATE INDEX idx_nguoidung_email ON NGUOIDUNG(Email);